name: Build driver solution
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2022
    env:
      Solution_Path: kbfiltr.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          
      - name: List directory contents
        run: |
          dir exe\x64\${{ matrix.configuration }}
          dir sys\x64\${{ matrix.configuration }}
      
      - name: Zip Release Directory
        run: |
          powershell Compress-Archive -Path exe\x64\${{ matrix.configuration }} -DestinationPath ${{ matrix.configuration }}.zip
          powershell Compress-Archive -Path sys\x64\${{ matrix.configuration }} -DestinationPath ${{ matrix.configuration }}.zip -Update
      
